spring:
    application:
        name: realtime-chatapp-user-service
    config:
        import: "configserver:"

    cloud:
        config:
            discovery:
                enabled: true
                service-id: realtime-chatapp-config-service
            fail-fast: true

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
